name: gezify
description: "Seyahat planlama projesi"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.6.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI ve ikonlar
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.17
  animated_splash_screen: ^1.3.0
  lottie: ^3.3.1

  # Durum yönetimi
  flutter_bloc: ^9.1.0
  hydrated_bloc: ^10.0.0
  path_provider: ^2.1.5
  equatable: ^2.0.5
  shared_preferences: ^2.2.2

  # Firebase
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.6.7

  # Takvim
  table_calendar: ^3.0.8

  # HTTP ve API
  http: ^1.4.0
  geolocator: ^10.1.0
  intl: ^0.18.1
  flutter_dotenv: ^5.1.0
  carousel_slider: ^5.0.0
  cached_network_image: ^3.2.3
  google_maps_flutter: ^2.12.2
  permission_handler: ^12.0.0+1
  fluttertoast: ^8.2.12
  uuid: ^4.5.1
  flutter_polyline_points: ^2.1.0
  smooth_page_indicator: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    -  assets/Lottie/animation4.json
    - assets/fonts/
    - assets/images/
    - assets/icons/
    # - assets/vectors/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
        - asset: assets/fonts/Poppins-ExtraBold.ttf
        - asset: assets/fonts/Poppins-Light.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
