// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcn3x8Ja6qeaWb6Yxv722xyMBfMsiuYZ4',
    appId: '1:594086955691:web:57644684035e4ffbc885ee',
    messagingSenderId: '594086955691',
    projectId: 'gezify-f8e1e',
    authDomain: 'gezify-f8e1e.firebaseapp.com',
    storageBucket: 'gezify-f8e1e.firebasestorage.app',
    measurementId: 'G-7PMXR8FZQ8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmW_Pw-f_z6v2o_wo13Nmmytbr50VjA7w',
    appId: '1:594086955691:android:112f4f67c0816b34c885ee',
    messagingSenderId: '594086955691',
    projectId: 'gezify-f8e1e',
    storageBucket: 'gezify-f8e1e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXCPKqjyVQikJ1C6A4ZSXXJ1w2Y9n0f8M',
    appId: '1:594086955691:ios:7483000fccd9b486c885ee',
    messagingSenderId: '594086955691',
    projectId: 'gezify-f8e1e',
    storageBucket: 'gezify-f8e1e.firebasestorage.app',
    iosBundleId: 'com.example.gezify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXCPKqjyVQikJ1C6A4ZSXXJ1w2Y9n0f8M',
    appId: '1:594086955691:ios:7483000fccd9b486c885ee',
    messagingSenderId: '594086955691',
    projectId: 'gezify-f8e1e',
    storageBucket: 'gezify-f8e1e.firebasestorage.app',
    iosBundleId: 'com.example.gezify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBcn3x8Ja6qeaWb6Yxv722xyMBfMsiuYZ4',
    appId: '1:594086955691:web:209ed84f432a5e05c885ee',
    messagingSenderId: '594086955691',
    projectId: 'gezify-f8e1e',
    authDomain: 'gezify-f8e1e.firebaseapp.com',
    storageBucket: 'gezify-f8e1e.firebasestorage.app',
    measurementId: 'G-GG2TFHT9V5',
  );

}